[package]
name = "supabase-actix-auth_middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-web-httpauth = "0.8.2"
jwt-simple = "0.12.10"
serde = { version = "1.0", features = ["derive"] }

